/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tejas
 */
public class test1 extends javax.swing.JFrame {

    String[] cms = {"Tejas","Sajet","Laxmy","Rahul","Ankur","Adharsh","Abhay","Bharath","Karthik","Angel"};
    String[] cme = {"Dhanush","Supreeth","Namrutha","Yashasvini","Sparsha","Pani","Manasa","Harshitha","Anjali","Yana"};
    String[][] sect = {cms,cme};
    String c;
    int j;
    String[] d;
    int[] absent = new int[10];
    Connection cn;
    PreparedStatement st;
    /**
     * Creates new form test1
     */
    
    DefaultTableModel model;
    
    public test1() throws ClassNotFoundException {
        initComponents();
        model = (DefaultTableModel) tbl.getModel();
        Connect();
        //try{
        //    Class.forName("com.mysql.cj.jdbc.Driver");
        //    cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
       //     st=(PreparedStatement) cn.createStatement();
       //     JOptionPane.showMessageDialog(null, "connected");
       // }catch(HeadlessException | ClassNotFoundException | SQLException e){
       //     JOptionPane.showMessageDialog(null, "Not connected");
       // }
        //setVisible(true);
        //setLocationRelativeTo(null);
    }
    
     public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_a = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_d = new javax.swing.JLabel();
        pnl_center = new javax.swing.JPanel();
        pnl_a = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_cl = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        btn_sub = new javax.swing.JButton();
        pnl_d = new javax.swing.JPanel();
        tb = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(77, 19, 209));

        jPanel2.setBackground(new java.awt.Color(77, 19, 209));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("ATTENDANCE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(77, 19, 209));

        jPanel1.setBackground(new java.awt.Color(77, 19, 209));

        lbl_a.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_a.setText("ABSENTEE NO");
        lbl_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(77, 19, 209));

        lbl_d.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_d.setText("   DISPLAY");
        lbl_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_d, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_d, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        pnl_center.setLayout(new java.awt.CardLayout());

        pnl_a.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Enter the students number with 1 space between them.");

        cb_cl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CMS", "CME" }));

        jLabel3.setText("Class:");

        btn_sub.setText("Submit");
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_aLayout = new javax.swing.GroupLayout(pnl_a);
        pnl_a.setLayout(pnl_aLayout);
        pnl_aLayout.setHorizontalGroup(
            pnl_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aLayout.createSequentialGroup()
                .addGroup(pnl_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_aLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btn_sub))
                    .addGroup(pnl_aLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_aLayout.createSequentialGroup()
                .addGroup(pnl_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_aLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_aLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cb_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        pnl_aLayout.setVerticalGroup(
            pnl_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(pnl_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_sub)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pnl_center.add(pnl_a, "card2");

        pnl_d.setBackground(new java.awt.Color(204, 204, 204));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.getTableHeader().setReorderingAllowed(false);
        tb.setViewportView(tbl);

        javax.swing.GroupLayout pnl_dLayout = new javax.swing.GroupLayout(pnl_d);
        pnl_d.setLayout(pnl_dLayout);
        pnl_dLayout.setHorizontalGroup(
            pnl_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        pnl_dLayout.setVerticalGroup(
            pnl_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_dLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        pnl_center.add(pnl_d, "card3");

        getContentPane().add(pnl_center, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseclicked
        // TODO add your handling code here:
        if(evt.getSource()==lbl_a) {
            pnl_a.setVisible(true);
            pnl_d.setVisible(false);
        }
        if(evt.getSource()==lbl_d) {
            pnl_d.setVisible(true);
            pnl_a.setVisible(false);
        }
    }//GEN-LAST:event_mouseclicked

    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        if(evt.getSource()==lbl_a){
            jPanel1.setBackground(new Color(135,135,135));
        }
        if(evt.getSource()==lbl_d){
            jPanel4.setBackground(new Color(135,135,135));
        }
    }//GEN-LAST:event_mouseentered

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited
        // TODO add your handling code here:
        if(evt.getSource()==lbl_a){
            jPanel1.setBackground(new Color(77,19,209));
        }
        if(evt.getSource()==lbl_d){
            jPanel4.setBackground(new Color(77,19,209));
        }
    }//GEN-LAST:event_mouseexited

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        // TODO add your handling code here:
        if(validation()){
            c = cb_cl.getSelectedItem().toString();
            d = tf1.getText().split(" ");
            add();
            for(int i = 0;i<d.length;i++){
                System.out.println(absent[i]+" "+j);
            }
        }
        else{
            reset();
        }
        
        
    }//GEN-LAST:event_btn_subActionPerformed

    private boolean validation(){
        if(tf1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(test1.this, "Enter th numbers!!");
            tf1.grabFocus();
            return false;
        }
        return true;
    }
    
    private void reset(){
        tf1.setText("");
    }
    
    private void add(){
        int sl1;
        String name;
        if (c.equals("CMS")){
            j = 0;
        }
        else{
            j=1;
        }
        for(int i = 0;i<d.length;i++){
            absent[i] = Integer.parseInt(d[i]);
        }
        for(int i=0;i<d.length;i++){
            sl1 = i + 1;
            name = sect[j][absent[i]];
            try {
                st=cn.prepareStatement("insert into student(sl,Name)values(?,?)");
            } catch (SQLException ex) {
                Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                st.setInt(1, sl1);
            } catch (SQLException ex) {
                Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                st.setString(2, name);
            } catch (SQLException ex) {
                Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                st.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this,"Record has added");
            model.insertRow(tbl.getRowCount(), new Object[]{
                i+1,
                sect[j][absent[i]]
            });
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new test1().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(test1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sub;
    private javax.swing.JComboBox<String> cb_cl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_d;
    private javax.swing.JPanel pnl_a;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_d;
    private javax.swing.JScrollPane tb;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
